language: node_js
node_js:
  - 8.11.3
branches:
  only:
    - src
cache: yarn
script:
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: src
  target-branch: master
  local-dir: public